### ISSUE TITLE
TinyStrAuto

### ISSUE THREAD

**Issue by sffc** [zbraniecki/tinystr#12]
It might be nice to have something like "MaybeTinyStr" or "TinyStrAuto" that chooses the right size of TinyStr based on the input, and falls back to String when the input is too long.

See https://github.com/i18n-concept/rust-discuss/pull/16#issuecomment-585492828

**Comment by zbraniecki** [comment]
Merged!

Would it make sense to try to use smaller TinyStr's for shorter strings, or is it not worth the hassle?

Also, would be nice to add some docs.

**Comment by sffc** [comment]
> Would it make sense to try to use smaller TinyStr's for shorter strings, or is it not worth the hassle?

I was thinking about this, but it doesn't actually make much of a difference because String is 24 bytes, so we don't get any gain in terms of stack size by using a smaller type.  The only potential advantage would come from faster bitwise operations.

> Also, would be nice to add some docs.

Right, and you also left a comment about another test.  I'm still working on that and will push it to my branch soon (and open a new PR).

**Comment by sffc** [comment]
Could you release a version of TinyStr with TinyStrAuto?

**Comment by zbraniecki** [comment]
Done!
