### ISSUE TITLE
Macros should accept a token tree that resolves to a string

### ISSUE THREAD

**Issue by sffc** [zbraniecki/tinystr#24]
I'm having trouble using the new tinystr macros inside of another macro.  If I apply the following patch, I get an error: "error: proc macro panicked ... message: Argument must be a string literal" (see https://github.com/unicode-org/icu4x/pull/307):

```
diff --git a/components/data-provider/src/data_key.rs b/components/data-provider/src/data_key.rs
index 0563c6c..af317b4 100644
--- a/components/data-provider/src/data_key.rs
+++ b/components/data-provider/src/data_key.rs
@@ -3,6 +3,7 @@ use std::borrow::Cow;
 use std::fmt;
 use std::fmt::Write;
 use tinystr::TinyStr16;
+use tinystr_macros::tinystr16;
 /// A top-level collection of related data keys.
 #[non_exhaustive]
@@ -79,8 +80,7 @@ macro_rules! icu_data_key {
     ($category:expr, $sub_category:tt, $version:tt) => {
         $crate::DataKey {
             category: $category,
-            // TODO: Parse to TinyStr at compile time
-            sub_category: stringify!($sub_category).parse().unwrap(),
+            sub_category: tinystr_macros::tinystr16!(stringify!($sub_category)),
             version: $version,
         }
     };
```

I suggested that we should look into using `stringify!` instead.

This change should also be made to the `get_value_from_token_stream` function in the locale macros in ICU4X.

**Comment by zbraniecki** [comment]
This will make it not work in `const` locations because of runtime computations.

**Comment by sffc** [comment]
> This will make it not work in `const` locations because of runtime computations.

In my example, the string is still known at compile time, but it gets passed down as a macro rules argument (`$sub_category`).  So, no, it should have no effect on constness.

**Comment by sffc** [comment]
From https://github.com/zbraniecki/tinystr/pull/26:

> I decided to keep the macros as requiring string literals `"..."`. I've learned that the Rust compiler tokenizes the source text before passing it into the proc macro, so it's not semantically correct for us to accept a token tree (`tt`) or identifier (`ident`), since the grammar for those tokens does not cover the TinyStr grammar of all ASCII characters. For example, if you want `tinystr!("a$b")`, it's not possible to write it without the quotes like `tinystr!(a$b)`.
