### ISSUE TITLE
Investigate performance of binary search on a vector of TinyStrs

### ISSUE THREAD

**Issue by dminor** [zbraniecki/tinystr#39]
In https://github.com/unicode-org/icu4x/pull/504, we're seeing a significant performance win by changing the representation from TinyStr4 to a raw u32. I spent a little time investigating this, and we're definitely generating [different code](https://github.com/unicode-org/icu4x/pull/504#issuecomment-785874662) for Ord depending on whether or not we're using a NonZeroU32 or a raw u32.

I've added a benchmark to help investigate this in TinyStr, but we still need to profile and see if the difference in performance comes from the different Ord implementations or if there is another problem. Ideally, there would be a minimal overhead from using NonZeroU32 in place of u32. The use of NonZeroU32 allows us to store Unique<TinyStr4> in the same space as a u32, so it seems like switching to use u32 would be a space/performance trade that we would not want to make.

**Comment by sffc** [comment]
Also, I realized that we might need a custom Ord implementation anyway, in order to have the same behavior on little endian vs big endian.

**Comment by zbraniecki** [comment]
I added an IAI benchmark for the behavior we're chasing after: https://github.com/zbraniecki/tinystr/blob/master/benches/bench_iai.rs

Results as of today:

```rust
▶ cargo criterion iai_tinystr                
   Compiling tinystr v0.4.3 (/projects/tinystr)

    Finished bench [optimized] target(s) in 0.29s
iai_tinystr
  Instructions:                 100 (No change)
  L1 Accesses:                  126 (No change)
  L2 Accesses:                    0 (No change)
  RAM Accesses:                   4 (No change)
  Estimated Cycles:             266 (No change)

iai_tinystr_as_unsigned
  Instructions:                   1 (No change)
  L1 Accesses:                    2 (No change)
  L2 Accesses:                    1 (No change)
  RAM Accesses:                   0 (No change)
  Estimated Cycles:               7 (No change)
```

@dminor @sffc @Manishearth - can I get another pair of eyeballs that I'm measuring the right thing?

**Comment by sffc** [comment]
Two thoughts:

1. The compiler is probably pre-computing the result in as_unsigned; consider adding a black_box around the slice to prevent this
2. I think part of the problem may come from the NonZeroU32 to u32 not being inlined. Can we force it to be inlined?

**Comment by zbraniecki** [comment]
> The compiler is probably pre-computing the result in as_unsigned; consider adding a black_box around the slice to prevent this

That helped. Thanks!

I added black_box and now the size of the array impacts the results. The results are:

Result:

```
iai_tinystr
  Instructions:                 137 (No change)
  L1 Accesses:                  173 (No change)
  L2 Accesses:                    0 (No change)
  RAM Accesses:                   5 (No change)
  Estimated Cycles:             348 (No change)

iai_tinystr_as_unsigned
  Instructions:                  53 (No change)
  L1 Accesses:                   63 (No change)
  L2 Accesses:                    0 (No change)
  RAM Accesses:                   3 (No change)
  Estimated Cycles:             168 (No change)
```

which seems in line with expectations.

> I think part of the problem may come from the NonZeroU32 to u32 not being inlined. Can we force it to be inlined?

I haven't gotten to investigate the fix, first I want to get a reliable measurement.

I'm going to start looking into the assembly and inlining now.
