### ISSUE TITLE
Refactor to single source file?

### ISSUE THREAD

**Issue by BartMassey** [zbraniecki/tinystr#4]
If you look at my [merge-types](/BartMassey/tinystr/tree/merge-types) branch you will find a bunch of macro work to replace the multiple implementation files with a single common one. Benchmarking indicates performance is about the same, as one would expect since I tried hard to generate the same code as before. The macro approach is not the most beautiful, but I despaired of playing the right games to get this performant with traits given the current state of stable Rust.

I didn't put in a PR because I didn't know if you wanted to go this route. I will if you like.

**Comment by Manishearth** [comment]
Since this issue the implementation has changed to use const generics, and the impls are now unified.

Thanks for investigating this, though!
