### ISSUE TITLE
Figure out endianness story

### ISSUE THREAD

**Issue by Manishearth** [zbraniecki/tinystr#45]
Right now TinyStr contains an integer that can be interpreted as a string. There are also ways of looking at TinyStr as an integer, both by looking at the integer in the native endianness, and by converting it to a little-endian representation that can be sent across machines.

The conversion methods are kinda haphazard, https://github.com/zbraniecki/tinystr/pull/43 completes the set but really we should figure out what utilities we _want_ to expose for viewing the TinyStr as an integer and stick to those.

Furthermore, it's unclear to me if the `tinystr!()` macro is sound when cross compiling: if you build your code on a little endian system targeting big endian, will the codegen use the little endian representation? It's kinda tricky to investigate, and our constructors from numbers should probably be exceedingly clear about this.

Ideally we can add dedicated constructors for the ULE use case (https://github.com/zbraniecki/tinystr/pull/44)

**Comment by sffc** [comment]
Related: https://github.com/rust-lang/rust/issues/76976

**Comment by Manishearth** [comment]
Yeah, I like this idea!

**Comment by sffc** [comment]
@zbraniecki, thoughts? Would you approve a PR that does what the OP proposes?

**Comment by zbraniecki** [comment]
I'm ok with that change, but I'd be curious what the performance impact may be.

**Comment by Manishearth** [comment]
I don't think there will be one, we're just changing the types used, not runtime behavior

**Comment by sffc** [comment]
Discussion with me and Manish: we can have `AsciiULE<N>` and `TinyStrN` where N is 1 to 16, and `TinyStrN` is a wrapper around `AsciiULE<N>` but `repr(align(...))`.

**Comment by Manishearth** [comment]
Fixed by https://github.com/unicode-org/icu4x/pull/1508

**Comment by Manishearth** [comment]
@zbraniecki should we mark this repo as archived and point to icu4x?
