### ISSUE TITLE
example code in README.md looks wrong

### ISSUE THREAD

**Issue by snaar** [zbraniecki/tinystr#52]
It has this:
```
    let s5: TinyStrAuto = "longFallbackToHeap".parse().unwrap();
    assert!(matches!(s4, TinyStrAuto::Heap { .. }));
    assert_eq!(s4, "shortNoAlloc");
```
It looks like this block should be referring to s5 instead of s4.

**Comment by Manishearth** [comment]
The readme has changed drastically since

(This repo is going to be archived soon, the up-to-date source is in https://github.com/unicode-org/icu4x)
