### ISSUE TITLE
TinyStrAuto is 32-bytes large, larger than the String

### ISSUE THREAD

**Issue by kornelski** [zbraniecki/tinystr#58]
`String` is 24 bytes large, but because `TinyStrAuto` is a regular Rust `enum`, it adds an extra usize for the tag, so it's *larger* than a regular string. Not tiny at all ;(

I expected it to be an `unsafe` union that takes advantage of `String`'s layout to store data over its pointer and capacity fields when len allows. 

This is 24 bytes:

```rust
enum Auto {
    Small([u8; 23]),
    Big(Box<str>),
}
```

This is 32 bytes:

```rust
enum Auto {
    Small([u8; 31]),
    Big(String),
}
```

So even in safe Rust using only 16 bytes inline is suboptimal.

**Comment by Cypher1** [comment]
@kornelski are you interested in implementing this or is it just an observation?

Also, when you say "`String`'s layout" is this that the pointer and capacity have alignment and range requirements in this context or something more subtle?

**Comment by Manishearth** [comment]
The latest version of this crate (0.7.0) no longer has this type, FWIW. We're open to adding one again with that optimization.

**Comment by Cypher1** [comment]
Could the documentation be updated in that case?

**Comment by Manishearth** [comment]
Whose documentation? The type doesn't exist anymore.

**Comment by Cypher1** [comment]
Isn't it in the readme still?

**Comment by Manishearth** [comment]
Ah, fair, though this repo isn't where the crate is maintained anymore and we plan to update it to point to unicode-org/icu4x anyway

**Comment by sffc** [comment]
For what it's worth, I'm no longer convinced TinyStrAuto is the best design choice; if you have variable-length strings, you should opt for a data structure that stores them efficiently all the time, like [VarZeroVec](https://icu4x.unicode.org/doc/zerovec/enum.VarZeroVec.html). It's possible that TinyStrAuto is useful to others, but at least for ICU4X's use case, it's not something we use any more.
