### ISSUE TITLE
Question on zero-length string errors + default trait implementation

### ISSUE THREAD

**Issue by noamteyssier** [zbraniecki/tinystr#59]
Hello - this is a great crate.

I was curious why a zero-length string is excluded from the structs and results in errors?

If this was included then it would be straightforward to implement a default trait on each of these which could be useful in a lot of contexts for generics that include strings and byte strings. 

Would be happy to work on if there's interest - also just curious on the design choice

**Comment by Manishearth** [comment]
The core reason is that it lets `Option<TinyAsciiStr>` always be the same size as the underlying strong.

If you want to use null as a default/sentinel I would recommend using the Option type instead.
