### ISSUE TITLE
is_ascii_alphanumeric doesn't work

### ISSUE THREAD

**Issue by zbraniecki** [zbraniecki/tinystr#8]
While working on migrating unic_locale to TinyStr I noticed that the following test fails:

```rust
    assert!("h12"
        .parse::<TinyStr4>()
        .unwrap()
        .is_ascii_alphanumeric())

    assert!("h12"
        .parse::<TinyStr8>()
        .unwrap()
        .is_ascii_alphanumeric())
```

**Comment by zbraniecki** [comment]
@raphlinus @BartMassey - maybe either of you will have time to debug it? If not, I'll try to look into it tomorrow.

**Comment by raphlinus** [comment]
Hmm, yes, this tests [a-zA-Z]. I can fix it.

**Comment by BartMassey** [comment]
Yeah, I was looking at it as well. I was just working through the bitmath, which is a little fancy.

Do we want to have `is_ascii_lowercase()`, `is_ascii_uppercase()`, `is_ascii_alpha()` etc etc? Special handling for '`_`', that kind of thing?

**Comment by zbraniecki** [comment]
I wanted to shadow what Rust STD does for char. For langid/locale I need "is_alohanumeric", "is_numeric", "is_alphabetic" I believe.

**Comment by raphlinus** [comment]
I can do that. The char method is called "is_digit" but that seems wrong for a multi-character object. I'll go with what you suggest.

**Comment by zbraniecki** [comment]
Fixed in https://github.com/zbraniecki/tinystr/commit/9b1e294f392ea31e086f752e900fe21f74b7fb7a
